### ISSUE TITLE
Using other plugin's callbacks in PHP

### ISSUE THREAD

**Issue by maddin77** [Lapayo/SAMPHP#1]
Hi,
i want to use the functions of the [FCNPC Plugin](http://forum.sa-mp.com/showthread.php?t=428066) in PHP, but i cant find a way to use callbacks. I tried to use it like this:

```
RegisterAMXNative('FCNPC_OnCreate', "null", "int");
function FCNPC_OnCreate($id) {
    //do something
}
```

but that will just throw me an error because it will try to redeclare a function.

So... is there actually a way to do this? Or if not, are there any plans to implement this in the future?

**Comment by Lapayo** [comment]
At the moment this is not possible.
I dont have much time in the moment, so I dont know if or when it will be implemented.
