### ISSUE TITLE
Streamer plugin

### ISSUE THREAD

**Issue by FPNDev** [Lapayo/SAMPHP#15]
Why can't i register streamer natives?

```
RegisterAMXNative('CreateDynamicPickup', 'int', 'int', 'int', 'float', 'float', 'float', 'int', 'int', 'int', 'float', 'int', 'int');
RegisterAMXNative('DestroyDynamicPickup', null, 'int');
RegisterAMXNative('IsValidDynamicPickup', 'bool', 'int');
```

Running like:
`CreateDynamicPickup(1318, 1, 0, 0, 0, 0, 0, -1, 200, -1, 0);`

Trying to do like that, but it's not working

Streamer plugin is installed and ran sucessfully.

**Comment by AmirSavand** [comment]
@FPNDev SAMPHP does not support Streamer plugin.

Check #12

**Comment by FPNDev** [comment]
@AmirSavand , checked this, but i thought registering plugin natives is supported. Don't you know any other plugins, that could help me with dynamic objects, pickups and etc? Would be grateful

**Comment by AmirSavand** [comment]
@FPNDev I tried using this framework but it's not possible to make a good gamemode out of it, this project is dead and it's pretty outdated, the source code also has issues that needs to be fixed manually, like old functions and missing parameters, etc...

Also you will face random issues, like players getting disconnected, or random warnings about simple functions.

So your best option is not using Streamer at all or go back to Pawn 😉

**Comment by AmirSavand** [comment]
And I don't know any other way or plugins for this framework.

**Comment by AmirSavand** [comment]
@FPNDev you can however, use streamer in a filterscript or gamemode (not PHP) just like you use it without this framework, but you should also handle them via pawn (not PHP).

But this method requires some skills, not anyone can pull it off. But it's the only option to make it work with SAMPHP.

**Comment by FPNDev** [comment]
@AmirSavand, don't you know, is it possible to call my PHP function using pawn CallRemoteFunction? I've tried, but it's not working

**Comment by AmirSavand** [comment]
@FPNDev As far as I know, not possible to communicate between SAMPHP and normal SAMP gamemodes/filterscripts.

**Comment by FPNDev** [comment]
Damn, have to shitcode than. But, anyway, thx.

**Comment by AmirSavand** [comment]
But you can however, communicate via player variables or file system... But why go through so much trouble?

You should handle the streamer stuff in Pawn only....

**Comment by AmirSavand** [comment]
Yea good luck, you'll realize that Pawn is better later.
